/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Baitaplon.View;

import Baitaplon.Model.KhachHang;
import Baitaplon.Model.NhanVien;
import Baitaplon.Model.Phim;
import Baitaplon.Model.Phong;
import Baitaplon.controler.Files;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class HomeFrame extends javax.swing.JFrame {

    public ArrayList<Phong> Arrphong = new ArrayList<>();
    public ArrayList<NhanVien> ArrNhanVien = new ArrayList<>();
    public ArrayList<KhachHang> ArrKhachHang = new ArrayList<>();
    public ArrayList<Phim> ArrPhim = new ArrayList<>();
    DefaultTableModel modelA;
    DefaultTableModel modelB;
    DefaultTableModel modelC;
    DefaultTableModel modelD;
    private String duogndan="";
    private String duongdananhnv = null;
    private String anhdaidien = "C:\\Users\\LENOVO\\OneDrive\\Documents\\Java code\\code with netbeans\\Baitaplon\\app\\src\\main\\java\\Baitaplon\\Assest\\hinh-avatar-trang.jpg";
    private Files fos = new Files();
    /**
     * Creates new form FramePhong
     */
    public HomeFrame() {
        initComponents();
        setTitle("Quản Lý Rạp Chiếu Phim");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        modelA = (DefaultTableModel) Tablephong.getModel();
        modelB = (DefaultTableModel) TableNhanvien.getModel();
        modelC = (DefaultTableModel) TableKhachHang.getModel();
        modelD = (DefaultTableModel) Tablephim.getModel();
        lbanhnv.setIcon(ResizeImage(anhdaidien, lbanhnv));
        docPhong();
        docNhanVien();
        docKhachHang();
        docphim();
    }

    public ImageIcon ResizeImage(String ImagePath,JLabel lable){
        ImageIcon Myimage = new ImageIcon(ImagePath);
        Image img = Myimage.getImage();
        Image newImg = img.getScaledInstance(lable.getWidth(), lable.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return  image;
    }
    public String regular(String a)throws Exception{
        String regex = "^\\w+[a-z0-9]*@{1}\\w+mail.com$";
        Pattern patters = Pattern.compile(regex);
        Matcher mat = patters.matcher(a);
        if(mat.find()){
            return a;
        }else{
            throw new Exception();
        }
    }
    public String getduongdan(){
        return this.duogndan;
    }
    public void docPhong(){
        Arrphong = fos.docfile("QLPHONG.TXT");
        showdata(Arrphong, modelA);
    }
    public void docNhanVien(){
        ArrNhanVien = fos.docfile("QLNHANVIEN.TXT");
        showdata(ArrNhanVien, modelB);
    }
    public void docKhachHang(){
        ArrKhachHang = fos.docfile("QLKHACHHANG.TXT");
        showdata(ArrKhachHang, modelC);
    }
    public void docphim(){
        ArrPhim=fos.docfile("QLPHIM.TXT");
        showdata(ArrPhim, modelD);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablephong = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableNhanvien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextTenNV = new javax.swing.JTextField();
        TexttuoiNV = new javax.swing.JTextField();
        TextEmailNV = new javax.swing.JTextField();
        TextDCNV = new javax.swing.JTextField();
        RBSang = new javax.swing.JRadioButton();
        RBChieu = new javax.swing.JRadioButton();
        RBToi = new javax.swing.JRadioButton();
        TextLuong = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        lbanhnv = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbmanv = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbtennv = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbtuoinv = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lbEmailnv = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lbcalam = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbluong = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableKhachHang = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        TxtTenKH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtTuoiKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtEmailKH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtDiachiKH = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TxtTenTKKH = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        TxtPassKH = new javax.swing.JPasswordField();
        jButton8 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        labelanh = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tablephim = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtmaphim = new javax.swing.JLabel();
        txttenphim = new javax.swing.JLabel();
        txttheloai = new javax.swing.JLabel();
        txtngaychieu = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        ttenphim = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tngaychieu = new javax.swing.JTextField();
        combott = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        Tablephong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Số ghế", "Số lượng Phim Chiếu"
            }
        ));
        jScrollPane1.setViewportView(Tablephong);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(147, 41, 579, 320);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(6, 54, 130, 34);

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addphim.png"))); // NOI18N
        jButton2.setText("Xóa phòng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(6, 119, 130, 36);

        jButton3.setText("Xem phòng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(6, 253, 123, 34);

        jButton4.setText("Lưu phòng");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(6, 188, 123, 33);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("THÔNG TIN VỀ CÁC PHÒNG");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(228, 6, 330, 29);

        jButton5.setText("Thoát");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(6, 321, 123, 32);
        jPanel1.add(jLabel16);
        jLabel16.setBounds(14, 6, 43, 0);

        jTabbedPane1.addTab("Phòng", jPanel1);

        TableNhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã ", "Tên", "Tuôỉ", "Email", "Ca làm", "Hệ lương", "Địa Chỉ"
            }
        ));
        TableNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableNhanvienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableNhanvien);

        jLabel2.setText("Nhập Tên Nhân Viên:");

        jLabel3.setText("Nhập Tuổi Nhân Viên :");

        jLabel4.setText("Nhâp Email Nhân Viên : ");

        jLabel5.setText("Nhập Địa Chỉ Nhân Viên :");

        jLabel6.setText("Ca làm việc");

        jLabel7.setText("Hệ số lương : ");

        TextTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTenNVActionPerformed(evt);
            }
        });

        TexttuoiNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexttuoiNVActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBSang);
        RBSang.setText("Sáng");

        buttonGroup1.add(RBChieu);
        RBChieu.setText("Chiều");
        RBChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBChieuActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBToi);
        RBToi.setText("Tối");

        jButton6.setText("Thêm Nhân Viên");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Lưu file");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText("THÔNG TIN NHÂN VIÊN");

        jButton11.setText("Thoát");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton14.setText("Xóa nhân viên");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("jButton15");

        lbanhnv.setBackground(new java.awt.Color(255, 255, 255));
        lbanhnv.setText("                Ảnh ");

        jLabel17.setText("Mã nhân viên :");

        lbmanv.setText("Không có ");

        jLabel23.setText("Tên nhân viên :");

        lbtennv.setText("Không có ");

        jLabel25.setText("Tuổi nhân viên :");

        lbtuoinv.setText("Không có ");

        jLabel30.setText("Email : ");

        lbEmailnv.setText("Không có ");

        jLabel33.setText("Ca làm : ");

        lbcalam.setText("Không có ");

        jLabel35.setText("Hệ số lương :");

        lbluong.setText("Không có ");

        jButton16.setText("Chọn ảnh");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextTenNV)
                            .addComponent(TexttuoiNV)
                            .addComponent(TextEmailNV)
                            .addComponent(TextDCNV)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RBSang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBChieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RBToi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextLuong))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbanhnv, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jButton16)))
                                        .addGap(55, 55, 55)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbtennv, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbtuoinv, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEmailnv, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbcalam, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbluong, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(30, 30, 30)
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(TextTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TexttuoiNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextEmailNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbanhnv, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbtennv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtuoinv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmailnv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbcalam, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbluong, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TextDCNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBToi)
                            .addComponent(RBSang)
                            .addComponent(RBChieu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Nhân Viên", jPanel2);

        TableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ", "Họ Tên", "Tuổi", "Email", "Địa Chỉ", "Tài Khoản", "Mật Khẩu"
            }
        ));
        TableKhachHang.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TableKhachHangAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                TableKhachHangAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TableKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKhachHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableKhachHang);

        jLabel8.setText("Nhập Tên Khách Hàng : ");

        jLabel9.setText("Nhập Tuổi Khách Hàng : ");

        TxtTuoiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTuoiKHActionPerformed(evt);
            }
        });

        jLabel10.setText("Nhập Email Khách Hàng :");

        jLabel11.setText("Nhập Địa Chỉ Khách Hàng :");

        jLabel12.setText("Nhập Tên Tài Khoản Khách Hàng :");

        jLabel13.setText("Nhập Mật Khẩu cho Khách Hàng :");

        jButton8.setText("Thêm Khách Hàng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 0, 255));
        jLabel15.setText("THÔNG TIN KHÁCH HÀNG");

        jButton9.setText("Save as");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Thoát");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton21.setText("Reset");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setText("Xóa khách hàng");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTenKH)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(TxtTuoiKH)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtEmailKH)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtDiachiKH)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtTenTKKH)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtPassKH))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton8)
                .addGap(43, 43, 43)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton22)
                .addGap(38, 38, 38)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TxtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTuoiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtEmailKH, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtDiachiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtTenTKKH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPassKH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Khách hàng", jPanel3);

        labelanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelanh.setForeground(new java.awt.Color(255, 255, 255));
        labelanh.setText("                 Ảnh");

        jButton12.setText("Chọn ảnh");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        Tablephim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phim", "Tên phim", "Thể loại", "Ngày khởi chiếu"
            }
        ));
        Tablephim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablephimMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tablephim);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mã Phim :");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tên phim :");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Thể loại : ");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Ngày chiếu : ");

        txtmaphim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmaphim.setForeground(new java.awt.Color(255, 255, 255));
        txtmaphim.setText("Không có");

        txttenphim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttenphim.setForeground(new java.awt.Color(255, 255, 255));
        txttenphim.setText("Không có");

        txttheloai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttheloai.setForeground(new java.awt.Color(255, 255, 255));
        txttheloai.setText("Không có");

        txtngaychieu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtngaychieu.setForeground(new java.awt.Color(255, 255, 255));
        txtngaychieu.setText("Không có");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Tên phim :");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ngày khởi chiếu :");

        combott.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hài ", "Khoa học viễn tưởng", "Kinh dị", "Tình cảm", "Hoạt hình", "Ca nhạc", "Chiến tranh", "Hành động" }));

        jLabel28.setText("Thể loại : ");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("BẢNG QUẢN LÝ PHIM");

        jButton17.setText("Thêm phim vào phòng");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setText("Thêm phim");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Xóa phim");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setText("Lưu phim");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton13.setText("Làm mới");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttenphim, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tngaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addComponent(labelanh, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmaphim, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenphim, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtngaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combott, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel31))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(ttenphim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tngaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelanh, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtmaphim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txttenphim, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txttheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(txtngaychieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(combott, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("Phim", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int n;
        if(Arrphong.size()==0){
            n=100;
        }else{
            String a = Arrphong.get(Arrphong.size()-1).getMaph();
            a = a.substring(3);
            n = Integer.parseInt(a);
            n++;
        }
        int m = 100 + (Arrphong.size() * 60);
        String ma = "PHO"+n;
        Phong ph = new Phong(ma,m);
        Arrphong.add(ph);
        showdata(Arrphong,modelA);
        JOptionPane.showMessageDialog(rootPane, "Đã thêm 1 phòng");
        fos.ghifile(Arrphong, "QLPHONG.TXT");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int n=Tablephong.getSelectedRow();
        if(n==-1){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn phòng cần xóa","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            Arrphong.remove(n);
            JOptionPane.showMessageDialog(rootPane, "Xóa phòng thành công");
            showdata(Arrphong, modelA);
            fos.ghifile(Arrphong, "QLPHONG.TXT");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new InforPhongFra(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fos.ghifile(Arrphong, "QLPHONG.TXT");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TextTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTenNVActionPerformed

    private void TexttuoiNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexttuoiNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexttuoiNVActionPerformed

    private void RBChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBChieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBChieuActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String Ca = "";
        if(RBSang.isSelected()){
            Ca = "Sáng";
        }
        if(RBToi.isSelected()){
            Ca = "Tối";
        }
        if(RBChieu.isSelected()){
            Ca = "Chiều";
        }
        if(TextTenNV.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống tên nhân viên.");
        }else if(TexttuoiNV.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống tuổi nhân viên.");
        }else if(TextEmailNV.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống Email Nhân Viên");
        }else if(TextDCNV.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống địa chỉ");
        }else if(Ca.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn ca làm việc cho Nhân Viên");
        }else if(TextLuong.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống hệ số lương");
        }else if(duongdananhnv==null){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn ảnh","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            float heluong;
            int tuoi;
            try {
                tuoi = Integer.parseInt(TexttuoiNV.getText().trim());
                try {
                    String Email = regular(TextEmailNV.getText().trim());
                    try {
                    heluong = Float.parseFloat(TextLuong.getText());
                    int n;
                    if(ArrNhanVien.size()==0){
                        n=100;
                    }else{
                        String a = ArrNhanVien.get(ArrNhanVien.size()-1).getManv();
                        a = a.substring(3);
                        n= Integer.parseInt(a);
                        n++;
                    }
                    String ma = "NVI"+n;
                    NhanVien nv = new NhanVien(ma,heluong, Ca, TextTenNV.getText().trim(), tuoi, 
                    Email, TextDCNV.getText().trim(),duongdananhnv);
                    ArrNhanVien.add(nv);
                    duongdananhnv=null;
                    lbanhnv.setIcon(ResizeImage(anhdaidien, lbanhnv));
                    showdata(ArrNhanVien, modelB);
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã thêm một nhân viên");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, "Hệ số lương phải nhập số");
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Sai định dạng Email","Thông báo",JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Tuổi phải nhập số nguyên");
            }
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        fos.ghifile(ArrNhanVien, "QLNHANVIEN.TXT");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void TxtTuoiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTuoiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTuoiKHActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if(TxtTenKH.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống tên Khách Hàng");
        }else if(TxtTuoiKH.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống tuổi Khách Hàng.");
        }else if(TxtEmailKH.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống Email Khách Hàng.");
        }else if(TxtDiachiKH.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống địa chỉ Khách Hàng.");
        }else if(TxtTenTKKH.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống tên tài khoản khách hàng.");
        }else if(String.valueOf(TxtPassKH.getPassword()).trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Không được để trống mật khẩu tài khoản.");
        }else{
            int tuoi;
            try {
                tuoi = Integer.parseInt(TxtTuoiKH.getText().trim());
                try {
                    int n;
                    String ma;
                    if(ArrKhachHang.size()==0){
                        n=100;
                    }else{
                        String a = ArrKhachHang.get(ArrKhachHang.size()-1).getID();
                        a = a.substring(2);
                        n = Integer.parseInt(a);
                        n++;
                    }
                    ma = "KH"+n;
                    String Email = regular(TxtEmailKH.getText().trim());
                    //String diachi,String ID, String TenTK, String Email, String pass,String Hoten, int tuoi
                    KhachHang kh = new KhachHang(TxtDiachiKH.getText().trim(),ma, TxtTenTKKH.getText().trim(),
                        Email, String.valueOf(TxtPassKH.getPassword()).trim(),
                        TxtTenKH.getText().trim(), tuoi);
                    ArrKhachHang.add(kh);
                    showdata(ArrKhachHang, modelC);
                    JOptionPane.showMessageDialog(rootPane, "Đã thêm một khách hàng");
                    fos.ghifile(ArrKhachHang, "QLKHACHHANG.TXT");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Email chưa đúng định dạng","Thông báo",JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Tuổi phải nhập số nguyên.");
            }
        }
            
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        fos.ghifile(ArrKhachHang, "QLKHACHHANG.TXT");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser();
            f.setDialogTitle("Mở ảnh");
            f.showOpenDialog(null);
            File ftenanh = f.getSelectedFile();
            duogndan = ftenanh.getAbsolutePath();
            labelanh.setText("");
            labelanh.setIcon(ResizeImage(String.valueOf(duogndan).trim(),labelanh));
                
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn ảnh");
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void TableKhachHangAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TableKhachHangAncestorAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TableKhachHangAncestorAdded

    private void TableKhachHangAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TableKhachHangAncestorMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_TableKhachHangAncestorMoved

    private void TableKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKhachHangMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_TableKhachHangMouseClicked

    private void TablephimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablephimMouseClicked
        // TODO add your handling code here:
        
        int n = Tablephim.getSelectedRow();
        labelanh.setIcon(ResizeImage(String.valueOf(ArrPhim.get(n).getanh()),labelanh));
        txttenphim.setText(ArrPhim.get(n).getTenphim());
        txtmaphim.setText(ArrPhim.get(n).getMaphim());
        txttheloai.setText(ArrPhim.get(n).gettheloai());
        txtngaychieu.setText(ArrPhim.get(n).getngaycongchieu());
    }//GEN-LAST:event_TablephimMouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        int n;
        n = Tablephim.getSelectedRow();
        if(n==-1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn phim","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            String maph = null;
            try {
                maph = JOptionPane.showInputDialog(this,"Nhập mã phòng cần thêm phim","Nhập mã",
                JOptionPane.DEFAULT_OPTION);
                if(maph.trim().equals("")){
                    JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập mã phòng","Thông báo",JOptionPane.ERROR_MESSAGE);
                }else{
                    Phong pho = new Phong(maph.trim().toUpperCase());
                if(!Arrphong.contains(pho)){
                    JOptionPane.showMessageDialog(this, "Không tồn tại phòng này","Thông báo",JOptionPane.ERROR_MESSAGE);
                }else{
                    Phim phim = ArrPhim.get(n);
                    int i = Arrphong.indexOf(pho);
                    Arrphong.get(i).Arrphim.add(phim);
                    JOptionPane.showMessageDialog(rootPane, "Đã thêm 1 phim vào phòng "+maph.toUpperCase());
                    showdata(Arrphong, modelA);
                    }
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập phòng","Thông báo",JOptionPane.ERROR_MESSAGE);
            }
        }

        
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        System.out.println("hell");
        String theloai="";
        theloai=String.valueOf(combott.getSelectedItem()).trim();
        if(ttenphim.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập tên phim","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else if(tngaychieu.getText().trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn cần nhập ngày khởi chiếu.");
        }else if(theloai.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn cần chọn thể loại phim.");
        }else if(duogndan.trim().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn ảnh cho phim.");
        }else{
            int n;
            if(ArrPhim.size()==0){
                n=100;
            }else{
                String s = ArrPhim.get(ArrPhim.size()-1).getMaphim();
                s=s.substring(4);
                n=Integer.parseInt(s);
                n++;
            }
            String ma = "PHIM"+n;
            Phim phim = new Phim(ma, ttenphim.getText().trim(), 
                    tngaychieu.getText().trim(), duogndan, theloai);
            ArrPhim.add(phim);
            showdata(ArrPhim, modelD);
            labelanh.setIcon(null);
            labelanh.setText(" Ảnh");
            duogndan="";
            JOptionPane.showMessageDialog(rootPane, "Thêm phim thành công.");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        int n = Tablephim.getSelectedRow();
        if(n==-1){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn phim để xóa","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            ArrPhim.remove(n);
            showdata(ArrPhim, modelD);
            JOptionPane.showMessageDialog(rootPane, "Bạn đã xóa thành phim công ");
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        fos.ghifile(ArrPhim, "QLPHIM.TXT");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        ttenphim.setText("");
        tngaychieu.setText("");
        duogndan="";
        labelanh.setIcon(null);
        labelanh.setText("Ảnh");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser f = new JFileChooser();
            f.setDialogTitle("Mở ảnh");
            f.showOpenDialog(null);
            File ftenanh = f.getSelectedFile();
            duongdananhnv = ftenanh.getAbsolutePath();
            lbanhnv.setText("");
            lbanhnv.setIcon(ResizeImage(String.valueOf(duongdananhnv).trim(),lbanhnv));
                
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn ảnh","Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void TableNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableNhanvienMouseClicked
        // TODO add your handling code here:
        int n = TableNhanvien.getSelectedRow();
        NhanVien nv = ArrNhanVien.get(n);
        lbmanv.setText(nv.getManv());
        lbtennv.setText(nv.getHoten());
        String tuoi = String.valueOf(nv.getTuoi());
        lbtuoinv.setText(tuoi);
        lbEmailnv.setText(nv.getEmail());
        lbcalam.setText(nv.getCalam());
        String luong = String.valueOf(nv.getHesoluong());
        lbluong.setText(luong);
        lbanhnv.setIcon(ResizeImage(nv.getanh(), lbanhnv));
    }//GEN-LAST:event_TableNhanvienMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        int n=TableNhanvien.getSelectedRow();
        if(n==-1){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn nhân viên cần xóa","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            ArrNhanVien.remove(n);
            JOptionPane.showMessageDialog(rootPane, "Xóa nhân viên thành công");
            showdata(ArrNhanVien, modelB);
            fos.ghifile(ArrNhanVien, "QLNHANVIEN.TXT");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        int n = TableKhachHang.getSelectedRow();
        if(n==-1){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn khách hàng cần xóa","Thông báo",JOptionPane.ERROR_MESSAGE);
        }else{
            ArrKhachHang.remove(n);
            JOptionPane.showMessageDialog(rootPane, "Xóa khách hàng thành công");
            showdata(ArrKhachHang, modelC);
            fos.ghifile(ArrKhachHang, "QLKHACHHANG.TXT");
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        TxtTenKH.setText("");
        TxtTuoiKH.setText("");
        TxtEmailKH.setText("");
        TxtDiachiKH.setText("");
        TxtPassKH.setText("");
        TxtTenTKKH.setText("");
    }//GEN-LAST:event_jButton21ActionPerformed

    public <T> void showdata(ArrayList<T> list,DefaultTableModel model){
        model.setRowCount(0);
        for(T values : list){
            if(values instanceof Phong){
                Phong ph = (Phong) values;
                model.addRow(new Object[]{
                    ph.getMaph(),ph.getArrghe().size(),ph.getArrphim().size()
                });
            }if(values instanceof NhanVien){
                NhanVien nv = (NhanVien) values;
                model.addRow(new Object[]{
                    nv.getManv(),nv.getHoten(),nv.getTuoi(),nv.getEmail(),nv.getCalam(),
                    nv.getHesoluong(),nv.getDiachi()
                });
            }if(values instanceof KhachHang){
                KhachHang kh = (KhachHang) values;
                model.addRow(new Object[]{
                    kh.getID(),kh.getHoten(),kh.getTuoi(),kh.getEmail(),
                    kh.getDiachi(),kh.getTenTK(),kh.getPass()
                });
            }if(values instanceof Phim){
                Phim phim = (Phim) values;
                model.addRow(new Object[]{
                    phim.getMaphim(),phim.getTenphim(),phim.gettheloai(),phim.getngaycongchieu()
                });
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBChieu;
    private javax.swing.JRadioButton RBSang;
    private javax.swing.JRadioButton RBToi;
    private javax.swing.JTable TableKhachHang;
    private javax.swing.JTable TableNhanvien;
    private javax.swing.JTable Tablephim;
    private javax.swing.JTable Tablephong;
    private javax.swing.JTextField TextDCNV;
    private javax.swing.JTextField TextEmailNV;
    private javax.swing.JTextField TextLuong;
    private javax.swing.JTextField TextTenNV;
    private javax.swing.JTextField TexttuoiNV;
    private javax.swing.JTextField TxtDiachiKH;
    private javax.swing.JTextField TxtEmailKH;
    private javax.swing.JPasswordField TxtPassKH;
    private javax.swing.JTextField TxtTenKH;
    private javax.swing.JTextField TxtTenTKKH;
    private javax.swing.JTextField TxtTuoiKH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> combott;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelanh;
    private javax.swing.JLabel lbEmailnv;
    private javax.swing.JLabel lbanhnv;
    private javax.swing.JLabel lbcalam;
    private javax.swing.JLabel lbluong;
    private javax.swing.JLabel lbmanv;
    private javax.swing.JLabel lbtennv;
    private javax.swing.JLabel lbtuoinv;
    private javax.swing.JTextField tngaychieu;
    private javax.swing.JTextField ttenphim;
    private javax.swing.JLabel txtmaphim;
    private javax.swing.JLabel txtngaychieu;
    private javax.swing.JLabel txttenphim;
    private javax.swing.JLabel txttheloai;
    // End of variables declaration//GEN-END:variables
}
